name: Deploy

on:
  push:
    branches:
      - temp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          debug: true
          port: 22
          script_stop: true
          script: |
            su - manoj -c '
              cd /var/www/voiceofamuse.com &&
              git fetch origin &&
              git reset --hard origin/temp &&
              npm install &&
              npm run build &&
              pm2 restart all
            '